# Generated by Django 5.0.1 on 2024-02-15 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        height_field=50,
                        upload_to="user_icons/None/",
                        verbose_name="icon",
                        width_field=50,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="bio")),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="名"
                    ),
                ),
                (
                    "family_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="family name"
                    ),
                ),
                (
                    "web_site",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="web site"
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="affiliation",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="location"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=150, verbose_name="link URL")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                        verbose_name="profile",
                    ),
                ),
            ],
        ),
    ]
