# Generated by Django 5.0.1 on 2024-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="family_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="web_site",
        ),
        migrations.AddField(
            model_name="link",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="link name"),
            preserve_default=False,
        ),
    ]
