# Generated by Django 5.0.1 on 2024-02-24 12:13

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0002_remove_profile_family_name_remove_profile_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="link",
            new_name="url",
        ),
        migrations.AlterField(
            model_name="profile",
            name="icon",
            field=models.ImageField(
                blank=True,
                upload_to=profiles.models.Profile.icon_upload_url,
                verbose_name="icon",
            ),
        ),
    ]
