# Generated by Django 5.0.1 on 2024-01-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("time_logs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actualtime",
            name="date_measured",
        ),
        migrations.AlterField(
            model_name="timelog",
            name="planed_time",
            field=models.DurationField(verbose_name="planed time"),
        ),
    ]
