# Generated by Django 5.0.1 on 2024-01-24 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("time_logs", "0002_remove_actualtime_date_measured_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actualtime",
            old_name="actual_time",
            new_name="measured_time",
        ),
    ]
