# Generated by Django 5.0 on 2023-12-28 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlansPermittees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_assigned",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned"),
                ),
                (
                    "permittee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plans.plan"
                    ),
                ),
            ],
            options={
                "db_table": "plans_permittees",
            },
        ),
        migrations.AlterField(
            model_name="plan",
            name="permittee",
            field=models.ManyToManyField(
                related_name="plans",
                related_query_name="plan",
                through="plans.PlansPermittees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Plans_permittees",
        ),
    ]
