# Generated by Django 5.0.1 on 2024-01-08 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="planspermittees",
            name="permittee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="planspermittees",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plans.plan"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="permittees",
            field=models.ManyToManyField(
                related_name="plans",
                related_query_name="plan",
                through="plans.PlansPermittees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
