# Generated by Django 5.0 on 2024-01-01 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("plans", "0003_rename_permittee_plan_permittees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("order", models.IntegerField(verbose_name="order")),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                        verbose_name="plan",
                    ),
                ),
            ],
            options={
                "db_table": "stages",
            },
        ),
    ]
